exports.up = function (knex) {
  return knex.schema
    .table("slot", (slot) => {
      slot.integer("day");
    })
    .then(() => {
      return knex("slot").insert([
        { day: 2, hour: "00", minutes: "00" },
        { day: 2, hour: "00", minutes: "15" },
        { day: 2, hour: "00", minutes: "30" },
        { day: 2, hour: "00", minutes: "45" },
        { day: 2, hour: "01", minutes: "00" },
        { day: 2, hour: "01", minutes: "15" },
        { day: 2, hour: "01", minutes: "30" },
        { day: 2, hour: "01", minutes: "45" },
        { day: 2, hour: "02", minutes: "00" },
        { day: 2, hour: "02", minutes: "15" },
        { day: 2, hour: "02", minutes: "30" },
        { day: 2, hour: "02", minutes: "45" },
        { day: 2, hour: "03", minutes: "00" },
        { day: 2, hour: "03", minutes: "15" },
        { day: 2, hour: "03", minutes: "30" },
        { day: 2, hour: "03", minutes: "45" },
        { day: 2, hour: "04", minutes: "00" },
        { day: 2, hour: "04", minutes: "15" },
        { day: 2, hour: "04", minutes: "30" },
        { day: 2, hour: "04", minutes: "45" },
        { day: 2, hour: "05", minutes: "00" },
        { day: 2, hour: "05", minutes: "15" },
        { day: 2, hour: "05", minutes: "30" },
        { day: 2, hour: "05", minutes: "45" },
        { day: 2, hour: "06", minutes: "00" },
        { day: 2, hour: "06", minutes: "15" },
        { day: 2, hour: "06", minutes: "30" },
        { day: 2, hour: "06", minutes: "45" },
        { day: 2, hour: "07", minutes: "00" },
        { day: 2, hour: "07", minutes: "15" },
        { day: 2, hour: "07", minutes: "30" },
        { day: 2, hour: "07", minutes: "45" },
        { day: 2, hour: "08", minutes: "00" },
        { day: 2, hour: "08", minutes: "15" },
        { day: 2, hour: "08", minutes: "30" },
        { day: 2, hour: "08", minutes: "45" },
        { day: 2, hour: "09", minutes: "00" },
        { day: 2, hour: "09", minutes: "15" },
        { day: 2, hour: "09", minutes: "30" },
        { day: 2, hour: "09", minutes: "45" },
        { day: 2, hour: "10", minutes: "00" },
        { day: 2, hour: "10", minutes: "15" },
        { day: 2, hour: "10", minutes: "30" },
        { day: 2, hour: "10", minutes: "45" },
        { day: 2, hour: "11", minutes: "00" },
        { day: 2, hour: "11", minutes: "15" },
        { day: 2, hour: "11", minutes: "30" },
        { day: 2, hour: "11", minutes: "45" },
        { day: 2, hour: "12", minutes: "00" },
        { day: 2, hour: "12", minutes: "15" },
        { day: 2, hour: "12", minutes: "30" },
        { day: 2, hour: "12", minutes: "45" },
        { day: 2, hour: "13", minutes: "00" },
        { day: 2, hour: "13", minutes: "15" },
        { day: 2, hour: "13", minutes: "30" },
        { day: 2, hour: "13", minutes: "45" },
        { day: 2, hour: "14", minutes: "00" },
        { day: 2, hour: "14", minutes: "15" },
        { day: 2, hour: "14", minutes: "30" },
        { day: 2, hour: "14", minutes: "45" },
        { day: 2, hour: "15", minutes: "00" },
        { day: 2, hour: "15", minutes: "15" },
        { day: 2, hour: "15", minutes: "30" },
        { day: 2, hour: "15", minutes: "45" },
        { day: 2, hour: "16", minutes: "00" },
        { day: 2, hour: "16", minutes: "15" },
        { day: 2, hour: "16", minutes: "30" },
        { day: 2, hour: "16", minutes: "45" },
        { day: 2, hour: "17", minutes: "00" },
        { day: 2, hour: "17", minutes: "15" },
        { day: 2, hour: "17", minutes: "30" },
        { day: 2, hour: "17", minutes: "45" },
        { day: 2, hour: "18", minutes: "00" },
        { day: 2, hour: "18", minutes: "15" },
        { day: 2, hour: "18", minutes: "30" },
        { day: 2, hour: "18", minutes: "45" },
        { day: 2, hour: "19", minutes: "00" },
        { day: 2, hour: "19", minutes: "15" },
        { day: 2, hour: "19", minutes: "30" },
        { day: 2, hour: "19", minutes: "45" },
        { day: 2, hour: "20", minutes: "00" },
        { day: 2, hour: "20", minutes: "15" },
        { day: 2, hour: "20", minutes: "30" },
        { day: 2, hour: "20", minutes: "45" },
        { day: 2, hour: "21", minutes: "00" },
        { day: 2, hour: "21", minutes: "15" },
        { day: 2, hour: "21", minutes: "30" },
        { day: 2, hour: "21", minutes: "45" },
        { day: 2, hour: "22", minutes: "00" },
        { day: 2, hour: "22", minutes: "15" },
        { day: 2, hour: "22", minutes: "30" },
        { day: 2, hour: "22", minutes: "45" },
        { day: 2, hour: "23", minutes: "00" },
        { day: 2, hour: "23", minutes: "15" },
        { day: 2, hour: "23", minutes: "30" },
        { day: 2, hour: "23", minutes: "45" },
      ]);
    })
    .then(() => {
      return knex("slot").update({ day: 1 }).where("day", null);
    });
};

exports.down = function (knex) {
  return knex.schema.dropTableIfExists("slot");
};
